import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header, Navbar, FixedButtons, Footer } from '@/lib/components';

const inter = Inter({ subsets: ['latin'] });

import { getServerSession } from 'next-auth';
import SessionProvider from './Providers/SessionProvider';
import JotaiProvider from './Providers/JotaiProvider';

export const metadata: Metadata = {
  title: '陌聲一頁式廣告',
  description: 'Generated by create next app',
};

export default async function RootLayout(props: { children: React.ReactNode }) {
  const session = await getServerSession();
  return (
    <html lang='en'>
      <body className={`${inter.className} pt-12 pb-0 `}>
        <JotaiProvider>
          <SessionProvider session={session}>
            <Header />
            <Navbar />
            <div className='xl:max-w-4xl mx-auto'>{props.children}</div>
            <FixedButtons />
            <Footer />
          </SessionProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
